export enum PERMISSION {
    SPENDING_READ = 'SPENDING_READ',
    SPENDING_WRITE = 'SPENDING_WRITE',
    SPENDING_DELETE = 'SPENDING_DELETE',

    LOAN_READ = 'LOAN_READ',
    LOAN_WRITE = 'LOAN_WRITE',
    LOAN_DELETE = 'LOAN_DELETE',

    TIMEKEEPING_READ = 'TIMEKEEPING_READ',
    TIMEKEEPING_WRITE = 'TIMEKEEPING_WRITE',
    TIMEKEEPING_DELETE = 'TIMEKEEPING_DELETE',

    PROFILE_READ = 'PROFILE_READ',
    PROFILE_WRITE = 'PROFILE_WRITE',
    PROFILE_CHANGE_PASSWORD = 'PROFILE_CHANGE_PASSWORD',
    PROFILE_CHANGE_MODE = 'PROFILE_CHANGE_MODE',
    PROFILE_CHANGE_LANGUAGE = 'PROFILE_CHANGE_LANGUAGE',
    PROFILE_RECEIVE_EMAIL = 'PROFILE_RECEIVE_EMAIL',
    PROFILE_STATISTIC = 'PROFILE_STATISTIC',

    ANNOUNCE_READ = 'ANNOUNCE_READ',
    ANNOUNCE_WRITE = 'ANNOUNCE_WRITE',
    ANNOUNCE_DELETE = 'ANNOUNCE_DELETE',
    ANNOUNCE_CONFIG = 'ANNOUNCE_CONFIG',

    ACCOUNT_READ = 'ACCOUNT_READ',
    ACCOUNT_WRITE = 'ACCOUNT_WRITE',
    ACCOUNT_DELETE = 'ACCOUNT_DELETE',

    FEEDBACK = 'FEEDBACK',
    FEEDBACK_CONFIG = 'FEEDBACK_CONFIG',
}
